source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'DJViewiOS_Example', :exclusive => true do
  pod "DJViewiOS", :path => "../"
end

target 'DJViewiOS_Tests', :exclusive => true do
  pod "DJViewiOS", :path => "../"

  
end
